name: Bug Report
description: Report a reproducible defect in writing-agent
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please include enough details for maintainers to reproduce and diagnose quickly.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, model provider, and deployment mode
      placeholder: "Windows 11, Python 3.11, Ollama provider, local run"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Exact steps to trigger the issue
      placeholder: |
        1. Run ...
        2. Open ...
        3. Click ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      render: shell

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues first.
          required: true
        - label: I can reproduce this issue on the latest main branch.
          required: false
