@echo off
cd /d %~dp0
set WRITING_AGENT_USE_OLLAMA=0
set WRITING_AGENT_LLM_PROVIDER=openai
if "%WRITING_AGENT_OPENAI_BASE_URL%"=="" set WRITING_AGENT_OPENAI_BASE_URL=https://api.openai.com/v1
set WRITING_AGENT_OPENAI_MODEL=gpt-5.4
set WRITING_AGENT_MODEL=gpt-5.4
set WRITING_AGENT_RAG_USE_EMBEDDINGS=0
set WRITING_AGENT_ANALYSIS_TIMEOUT_S=45
set WRITING_AGENT_WORKERS=4
set WRITING_AGENT_WORKER_MODELS=gpt-5.4
set WRITING_AGENT_AGG_MODEL=gpt-5.4
set WRITING_AGENT_DRAFT_MAIN_MODEL=gpt-5.4
set WRITING_AGENT_DRAFT_SUPPORT_MODEL=gpt-5.4
set WRITING_AGENT_DRAFT_PARALLEL=1
set WRITING_AGENT_DRAFT_MAX_MODELS=1
set WRITING_AGENT_PER_MODEL_CONCURRENCY=3
.\\.venv\\Scripts\\python -m writing_agent.launch 1>run.out 2>run.err
