/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmeditor_free: (a: number, b: number) => void;
export const wasmeditor_checkpoint: (a: number) => void;
export const wasmeditor_deleteBackward: (a: number) => void;
export const wasmeditor_exportJson: (a: number) => [number, number, number, number];
export const wasmeditor_exportMarkdown: (a: number) => [number, number];
export const wasmeditor_find: (a: number, b: number, c: number) => any;
export const wasmeditor_getCursorPosition: (a: number) => any;
export const wasmeditor_getStats: (a: number) => any;
export const wasmeditor_importMarkdown: (a: number, b: number, c: number) => [number, number];
export const wasmeditor_insertCode: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmeditor_insertFigure: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmeditor_insertImage: (a: number, b: number, c: number) => void;
export const wasmeditor_insertLink: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmeditor_insertList: (a: number, b: number) => void;
export const wasmeditor_insertQuote: (a: number, b: number, c: number) => void;
export const wasmeditor_insertTable: (a: number, b: number, c: number) => void;
export const wasmeditor_insertText: (a: number, b: number, c: number) => void;
export const wasmeditor_layout: (a: number, b: number) => [number, number, number];
export const wasmeditor_listIndent: (a: number) => void;
export const wasmeditor_listOutdent: (a: number) => void;
export const wasmeditor_loadJson: (a: number, b: number, c: number) => [number, number];
export const wasmeditor_new: () => number;
export const wasmeditor_redo: (a: number) => void;
export const wasmeditor_replace: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmeditor_setHeading: (a: number, b: number) => void;
export const wasmeditor_tableDeleteColumn: (a: number) => void;
export const wasmeditor_tableDeleteRow: (a: number) => void;
export const wasmeditor_tableInsertColumn: (a: number) => void;
export const wasmeditor_tableInsertRow: (a: number) => void;
export const wasmeditor_toggleBold: (a: number) => void;
export const wasmeditor_toggleItalic: (a: number) => void;
export const wasmeditor_toggleStrikethrough: (a: number) => void;
export const wasmeditor_toggleUnderline: (a: number) => void;
export const wasmeditor_undo: (a: number) => void;
export const main: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
